import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowRight, BadgeCheck, CircleAlert, Database, ExternalLink, Route, ShieldCheck, Sparkles } from 'lucide-react';
import { childFromParents, dataVersion, estimateStats, findPal, pals, parentsForTarget, passives, solveRoute } from './calculators';
import './styles.css';

type ToolKey = 'hub' | 'breeding' | 'route' | 'iv' | 'stats' | 'passives' | 'one0' | 'data' | 'privacy' | 'terms';
type ResultState = { title: string; body: string; code?: string; severity?: 'ok' | 'warn' | 'error'; details?: React.ReactNode };

type SharePayload = Record<string, string | number | boolean | undefined>;
declare global {
  interface Window {
    palcalculatorEvents?: Array<{ event: string; payload: Record<string, unknown>; ts: string }>;
    palcalculatorTrack?: (event: string, payload: Record<string, unknown>) => void;
  }
}
function trackEvent(event: string, payload: Record<string, unknown> = {}) {
  window.palcalculatorEvents = window.palcalculatorEvents ?? [];
  window.palcalculatorEvents.push({ event, payload, ts: new Date().toISOString() });
  window.palcalculatorTrack?.(event, payload);
}
function shareUrl(tool: ToolKey, payload: SharePayload) {
  const route = routes.find((r) => r.key === tool) ?? routes[0];
  const params = new URLSearchParams();
  for (const [key, value] of Object.entries(payload)) if (value !== undefined && String(value).trim()) params.set(key, String(value));
  const path = `${route.path}${params.toString() ? `?${params.toString()}` : ''}`;
  return `${window.location.origin}${path}`;
}

const routes: Array<{ key: ToolKey; path: string; label: string; h1: string; description: string }> = [
  { key: 'hub', path: '/', label: 'Home', h1: 'PalCalculator: Palworld Breeding, IV, Stats & Passive Calculators', description: 'Unofficial fan-made Palworld 1.0 calculator hub for breeding routes, IV/stat checks, passive planning, and owned-Pal optimization.' },
  { key: 'breeding', path: '/breeding-calculator/', label: 'Breeding', h1: 'Palworld Breeding Calculator', description: 'Check real parent pairs, target parents, caveats, and route-solver handoffs.' },
  { key: 'route', path: '/breeding-route-calculator/', label: 'Route', h1: 'Palworld Breeding Route Calculator', description: 'Plan the shortest route found from owned Pals to a target Pal with visible constraints.' },
  { key: 'iv', path: '/iv-calculator/', label: 'IV', h1: 'Palworld IV Calculator', description: 'Estimate IV ranges from observed stats while showing formula assumptions and unsupported modifiers.' },
  { key: 'stats', path: '/stats-calculator/', label: 'Stats', h1: 'Palworld Stats Calculator', description: 'Preview expected HP, attack, and defense bands from selected base stat data.' },
  { key: 'passives', path: '/passive-skill-calculator/', label: 'Passives', h1: 'Palworld Passive Skill Calculator', description: 'Plan target passives with RNG caveats and no deterministic inheritance promises.' },
  { key: 'one0', path: '/palworld-1-0-breeding-calculator/', label: '1.0 Breeding', h1: 'Palworld 1.0 Breeding Calculator', description: 'A 1.0-focused entry point that shares the breeding calculator and data freshness copy.' },
  { key: 'data', path: '/data-sources/', label: 'Data Sources', h1: 'PalCalculator Data Sources & Update Policy', description: 'Dataset version, source policy, unsupported domains, and correction workflow.' },
  { key: 'privacy', path: '/privacy/', label: 'Privacy', h1: 'Privacy Policy', description: 'How PalCalculator handles local calculator state, share URLs, hosting logs, and analytics.' },
  { key: 'terms', path: '/terms/', label: 'Terms', h1: 'Terms of Use', description: 'Unofficial fan-site terms, caveats, and acceptable use.' },
];

function routeFromPath(): ToolKey {
  const path = window.location.pathname.endsWith('/') ? window.location.pathname : `${window.location.pathname}/`;
  return routes.find((r) => r.path === path)?.key ?? 'hub';
}
function useRoute() {
  const [current, setCurrent] = useState<ToolKey>(routeFromPath());
  function navigate(key: ToolKey) { const route = routes.find((r) => r.key === key)!; window.history.pushState({}, '', route.path); document.title = route.h1; setCurrent(key); trackEvent('page_view', { route: key, path: route.path }); }
  React.useEffect(() => { trackEvent('page_view', { route: current, path: window.location.pathname }); }, []);
  React.useEffect(() => { const onPop = () => setCurrent(routeFromPath()); window.addEventListener('popstate', onPop); return () => window.removeEventListener('popstate', onPop); }, []);
  return { current, navigate };
}
function DataBadge() { return <div className="data-badge"><Database size={16}/><span>{dataVersion.gameVersionLabel}</span><strong>{dataVersion.dataVersion}</strong></div>; }
function Disclaimer() { return <p className="disclaimer">PalCalculator is an unofficial fan-made tool and is not affiliated with, endorsed by, sponsored by, or approved by Pocketpair or the Palworld team. Palworld and related names are trademarks or properties of their respective owners.</p>; }
function Header({ current, navigate }: { current: ToolKey; navigate: (key: ToolKey) => void }) { return <header className="site-header"><a className="brand" href="/" onClick={(e) => { e.preventDefault(); navigate('hub'); }}><span className="brand-mark">PC</span><span>PalCalculator</span></a><nav aria-label="Primary navigation">{routes.filter(r => ['breeding','route','iv','stats','passives','data'].includes(r.key)).map(r => <a key={r.key} href={r.path} className={current === r.key ? 'active' : ''} onClick={(e) => { e.preventDefault(); navigate(r.key); }}>{r.label}</a>)}</nav></header>; }
function ToolHero({ route, navigate }: { route: (typeof routes)[number]; navigate: (key: ToolKey) => void }) { return <section className="hero"><div><p className="eyebrow">Unofficial fan-made Palworld tool</p><h1>{route.h1}</h1><p className="hero-copy">{route.description}</p><div className="hero-actions"><button className="primary" onClick={() => navigate('route')}>Start with a target Pal <ArrowRight size={18}/></button><button className="secondary" onClick={() => navigate('breeding')}>Calculate breeding</button></div></div><div className="hero-card"><DataBadge/><p>{pals.length} Pal records and real normal-formula breeding pairs are installed. Special combo overrides remain caveated until separately verified.</p><ul><li>Calculator UI above the fold</li><li>Copy/share URL state, no account wall</li><li>Visible caveats instead of fabricated certainty</li></ul></div></section>; }
function PalSelect({ label, value, onChange }: { label: string; value: string; onChange: (v: string) => void }) { return <label className="field"><span>{label}</span><input list="pal-options" value={value} placeholder="Example: Anubis, Jetragon, Orserk" onChange={(e) => onChange(e.target.value)} /><datalist id="pal-options">{pals.map(p => <option key={p.id} value={p.displayName}/>)}</datalist></label>; }
function ResultBox({ result }: { result: ResultState }) { return <div className={`result ${result.severity ?? 'warn'}`} role="status"><div className="result-title">{result.severity === 'ok' ? <BadgeCheck/> : <CircleAlert/>}<strong>{result.title}</strong></div><p>{result.body}</p>{result.code && <code>{result.code}</code>}{result.details}</div>; }
function ToolPanel({ title, icon, children }: { title: string; icon: React.ReactNode; children: React.ReactNode }) { return <section className="tool-panel"><div className="tool-title">{icon}<h2>{title}</h2></div><DataBadge/>{children}</section>; }
function CaveatList({ items }: { items: string[] }) { return <ul className="caveats">{items.map(i => <li key={i}>{i}</li>)}</ul>; }
function ShareControls({ tool, payload, resultTitle }: { tool: ToolKey; payload: SharePayload; resultTitle: string }) {
  const [status, setStatus] = useState('');
  const url = shareUrl(tool, payload);
  async function copyShareUrl() {
    trackEvent('share_copy', { tool, resultTitle });
    try { await navigator.clipboard.writeText(url); setStatus('Share URL copied.'); }
    catch { setStatus(url); }
  }
  return <div className="share-controls"><button className="secondary" onClick={copyShareUrl}>Copy/share result URL</button><a href={url} onClick={() => trackEvent('share_open', { tool })}>Open share URL</a>{status && <small>{status}</small>}</div>;
}

function BreedingCalculator({ one0=false }: { one0?: boolean }) {
  const [mode, setMode] = useState<'pair'|'target'>('pair'); const [a, setA] = useState('Penking'); const [b, setB] = useState('Bushi'); const [target, setTarget] = useState('Anubis');
  const result = useMemo<ResultState>(() => {
    if (mode === 'pair') { const r = childFromParents(a, b); if (!r.ok) return { title: 'Pair unavailable', body: r.error.message, code: r.error.code, severity: 'error' }; return { title: `${r.parentA.displayName} + ${r.parentB.displayName} → ${r.child.displayName}`, body: `Normal formula output for ${r.dataVersion}. Combo type: ${r.comboType}.`, code: r.ruleId, severity: 'ok', details: <CaveatList items={r.caveats.map(c => c.message)}/> }; }
    const r = parentsForTarget(target, 10); if (!r.ok) return { title: 'Target unavailable', body: r.error.message, code: r.error.code, severity: 'error' };
    return { title: `${r.resultCount} parent pairs found for ${r.target.displayName}`, body: `Showing the first ${r.pairs.length} sorted pairs.`, severity: 'ok', details: <ol className="pairs">{r.pairs.map((p, i) => <li key={i}>{p.parentA.displayName} + {p.parentB.displayName}</li>)}</ol> };
  }, [mode, a, b, target]);
  React.useEffect(() => { trackEvent(result.severity === 'ok' ? 'tool_success' : 'tool_error', { tool: one0 ? 'one0' : 'breeding', mode, code: result.code ?? '' }); }, [result.title, result.severity, result.code, mode, one0]);
  return <ToolPanel title={one0 ? 'Palworld 1.0 breeding workspace' : 'Breeding workspace'} icon={<Sparkles/>}><div className="segmented"><button className={mode==='pair'?'selected':''} onClick={() => setMode('pair')}>Pair to child</button><button className={mode==='target'?'selected':''} onClick={() => setMode('target')}>Target to parents</button></div>{mode === 'pair' ? <div className="grid two"><PalSelect label="Parent A" value={a} onChange={setA}/><PalSelect label="Parent B" value={b} onChange={setB}/></div> : <PalSelect label="Target child" value={target} onChange={setTarget}/>}<ResultBox result={result}/><ShareControls tool={one0 ? 'one0' : 'breeding'} payload={{ mode, a, b, target }} resultTitle={result.title}/><CaveatList items={["Normal breeding outputs use public CombiRank values and source caveats.", "Verified special-combo override data is not claimed in this build.", "Results depend on selected data version and patch changes."]}/></ToolPanel>;
}
function RouteSolver() {
  const [target, setTarget] = useState('Anubis'); const [owned, setOwned] = useState('Penking, Bushi'); const [maxGen, setMaxGen] = useState(3);
  const result = useMemo<ResultState>(() => { const r = solveRoute(target, owned, maxGen); if (!r.ok) return { title: 'Route unavailable', body: r.error.message, code: r.error.code, severity: 'error' }; return { title: r.targetAlreadyOwned ? `${r.target.displayName} already owned` : `Route found to ${r.target.displayName}`, body: `${r.generations} generation(s), ${r.missingPals.length} missing Pal(s), ${r.alternatives.length} alternative(s). Tie rule: ${r.tieBreakRule}.`, severity: 'ok', details: <ol className="timeline">{r.steps.map(s => <li key={s.stepIndex}><span>{s.stepIndex}</span><p>{s.parentA.displayName} + {s.parentB.displayName} → {s.child.displayName}</p></li>)}</ol> }; }, [target, owned, maxGen]);
  React.useEffect(() => { trackEvent(result.severity === 'ok' ? 'tool_success' : 'tool_error', { tool: 'route', code: result.code ?? '' }); }, [result.title, result.severity, result.code]);
  return <ToolPanel title="Route-first workspace" icon={<Route/>}><div className="grid two"><PalSelect label="Target Pal" value={target} onChange={setTarget}/><label className="field"><span>Max generations</span><input type="number" min={1} max={8} value={maxGen} onChange={(e)=>setMaxGen(Number(e.target.value))}/></label></div><label className="field"><span>Owned Pals (browser-local paste)</span><textarea value={owned} onChange={(e)=>setOwned(e.target.value)} placeholder="Example: Penking, Bushi" /></label><ResultBox result={result}/><ShareControls tool="route" payload={{ target, owned, maxGen }} resultTitle={result.title}/></ToolPanel>;
}
function IvStatsTool({ kind }: { kind: 'iv' | 'stats' }) {
  const [pal, setPal] = useState('Anubis'); const [level, setLevel] = useState(50); const [hp, setHp] = useState('500'); const [attack, setAttack] = useState('130'); const [defense, setDefense] = useState('100');
  const result = useMemo<ResultState>(() => { const r = estimateStats(pal, level, { hp: Number(hp), attack: Number(attack), defense: Number(defense) }); if (!r.ok) return { title: 'Stat estimate unavailable', body: r.error.message, code: r.error.code, severity: 'error' }; return { title: kind === 'iv' ? 'Caveated IV bands calculated' : 'Expected stat bands calculated', body: `${r.pal.displayName} level ${r.level}. Confidence: ${r.confidence}.`, code: r.formulaVersion, severity: 'ok', details: <pre>{JSON.stringify(kind === 'iv' ? r.ivRangeByStat : r.expectedStats, null, 2)}</pre> }; }, [pal, level, hp, attack, defense, kind]);
  React.useEffect(() => { trackEvent(result.severity === 'ok' ? 'tool_success' : 'tool_error', { tool: kind, code: result.code ?? '' }); }, [result.title, result.severity, result.code, kind]);
  return <ToolPanel title={kind === 'iv' ? 'IV estimate workspace' : 'Stats range workspace'} icon={<BadgeCheck/>}><div className="grid two"><PalSelect label="Pal" value={pal} onChange={setPal}/><label className="field"><span>Level</span><input type="number" min={1} max={60} value={level} onChange={(e)=>setLevel(Number(e.target.value))}/></label></div><div className="grid three"><label className="field"><span>Observed HP</span><input value={hp} onChange={(e)=>setHp(e.target.value)} inputMode="numeric" /></label><label className="field"><span>Observed Attack</span><input value={attack} onChange={(e)=>setAttack(e.target.value)} inputMode="numeric" /></label><label className="field"><span>Observed Defense</span><input value={defense} onChange={(e)=>setDefense(e.target.value)} inputMode="numeric" /></label></div><ResultBox result={result}/><ShareControls tool={kind} payload={{ pal, level, hp, attack, defense }} resultTitle={result.title}/><CaveatList items={["Outputs are broad ranges when rounding/modifiers create uncertainty.", "Exact Palworld reverse-engineering with all modifiers is unsupported in this build.", "No perfect IV or 100% accuracy claims are used."]}/></ToolPanel>;
}
function PassivePlanner() { const [target, setTarget] = useState('Anubis'); const [desired, setDesired] = useState('Artisan, Serious'); const valid = desired.split(',').map(s => s.trim().toLowerCase()).filter(Boolean).map(x => passives.find(p => p.displayName.toLowerCase() === x || p.id === x)); const result: ResultState = { title: findPal(target) ? 'Passive plan captured' : 'Target needs review', body: `${valid.filter(Boolean).length} desired passive(s) recognized. Candidate route logic stays caveated because inheritance odds are not claimed.`, code: 'PASSIVE_RNG_CAVEATED', severity: findPal(target) ? 'ok' : 'error' }; React.useEffect(() => { trackEvent(result.severity === 'ok' ? 'tool_success' : 'tool_error', { tool: 'passives', code: result.code ?? '' }); }, [result.title, result.severity, result.code]); return <ToolPanel title="Passive planner shell" icon={<ShieldCheck/>}><div className="grid two"><PalSelect label="Target Pal" value={target} onChange={setTarget}/><label className="field"><span>Desired passives</span><input value={desired} onChange={(e)=>setDesired(e.target.value)} placeholder="Example: Artisan, Serious" /></label></div><ResultBox result={result}/><ShareControls tool="passives" payload={{ target, desired }} resultTitle={result.title}/><CaveatList items={["Passive inheritance can involve RNG.", "Use as planning guidance, not certainty.", "Candidate parents/routes use the breeding route calculator plus caveats."]}/></ToolPanel>; }
function Hub({ navigate }: { navigate: (key: ToolKey) => void }) { return <><div className="cards">{routes.filter(r => ['breeding','route','iv','stats','passives','one0'].includes(r.key)).map(r => <button className="card" key={r.key} onClick={() => navigate(r.key)}><h3>{r.h1}</h3><p>{r.description}</p><span>{r.label} <ArrowRight size={14}/></span></button>)}</div><section className="content"><h2>Production data status</h2><p>This build replaces example-only data with a Palworld 1.0 public-web dataset: {pals.length} Pals, normal formula breeding pairs, aliases, passive seed data, selected base stats, and caveated stat formulas.</p></section></>; }
function DataSources() { return <section className="content"><h2>Data source status</h2><dl><dt>Game target</dt><dd>{dataVersion.gameVersionLabel}</dd><dt>Dataset build</dt><dd>{dataVersion.dataVersion}</dd><dt>Last updated</dt><dd>{dataVersion.lastUpdated}</dd><dt>Included domains</dt><dd>{dataVersion.includedDomains.join(', ')}.</dd><dt>Unsupported now</dt><dd>{dataVersion.unsupportedDomains.join(', ')}.</dd><dt>Correction path</dt><dd id="corrections">Use the owner support/contact path before launch; corrections should include Pal name, game version, source link, and reproduction notes.</dd></dl><h3>Sources</h3><ul>{dataVersion.sourceRefs.map((s) => <li key={s.id}><a href={s.url}>{s.label}</a> — {s.category}. {s.notes}</li>)}</ul><p>Competitor/community pages are not treated as official; outputs carry source/version caveats and unsupported domains are stated instead of guessed.</p></section>; }
function Privacy() { return <section className="content"><h2>Privacy summary</h2><p>PalCalculator is a static, Cloudflare-first calculator hub. MVP inputs such as selected Pals, owned-Pal text, stat fields, and passive choices are handled in the browser UI unless a later owner-approved backend design changes that.</p><ul><li>No account or payment is required for P0 calculators.</li><li>No server-side save-file or raw Palbox upload is implemented.</li><li>Share URLs may include selected Pals or settings; do not share private state.</li><li>Analytics provider is pending and must be disclosed before production analytics.</li></ul></section>; }
function Terms() { return <section className="content"><h2>Unofficial fan-site terms</h2><p>This site is provided as an independent fan tool. References to Palworld, Pal names, game mechanics, or related terms are for identification and compatibility purposes only.</p><ul><li>Do not rely on calculator output as guaranteed, official, always current, or perfectly accurate.</li><li>Results depend on selected data versions, source quality, game patches, formulas, modifiers, and RNG.</li></ul></section>; }
function JsonLd() { const json = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: 'PalCalculator', applicationCategory: 'GameApplication', operatingSystem: 'Web', offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' }, description: 'Unofficial fan-made Palworld calculator hub for breeding routes, IV/stat checks, passive planning, and owned-Pal optimization.' }; return <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(json) }} />; }
function App() { const { current, navigate } = useRoute(); const route = routes.find(r => r.key === current)!; return <><JsonLd/><Header current={current} navigate={navigate}/><main><ToolHero route={route} navigate={navigate}/>{current === 'hub' && <Hub navigate={navigate}/>} {current === 'breeding' && <BreedingCalculator/>} {current === 'one0' && <BreedingCalculator one0/>} {current === 'route' && <RouteSolver/>} {current === 'iv' && <IvStatsTool kind="iv"/>} {current === 'stats' && <IvStatsTool kind="stats"/>} {current === 'passives' && <PassivePlanner/>} {current === 'data' && <DataSources/>} {current === 'privacy' && <Privacy/>} {current === 'terms' && <Terms/>}</main><footer><Disclaimer/><div className="footer-links">{routes.filter(r => ['data','privacy','terms'].includes(r.key)).map(r => <a key={r.key} href={r.path} onClick={(e) => { e.preventDefault(); navigate(r.key); }}>{r.label}</a>)}<a href="/sitemap.xml">Sitemap <ExternalLink size={12}/></a></div></footer></>; }

createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>);
